version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - mcclowes
  assignees:
  - mcclowes
  ignore:
  - dependency-name: lodash
    versions:
    - 4.17.20
